name: Update
on:
  check_run:
    types: [completed]

jobs:
  send:
    name: Send new verison	
    runs-on: ubuntu-latest
    
    steps:
      - name: Check
        run: echo RUN CHECK
      - name: HTTP Client
        run: curl -X POST -H "Content-Type:application/json" --data '{"text":"This is a line of text in a channel.\nAnd this is another line of text."}' ${CONNECTOR_URL}
        env:
          CONNECTOR_URL: ${{ secrets.connectorUrl }}
